name: Example Job - Deploy Leantime

# FILL THE MISSING VALUES BELOW
on:
  workflow_dispatch:

env:
  AWS_REGION:
  ECR_REPOSITORY:
  ECS_CLUSTER:
  TOKEN: $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

  ECS_LEANTIME_SERVICE:
  LEANTIME_TASK_DEFINITION:
  LEANTIME_URL: "lks-oss-lb-180537770.us-east-1.elb.amazonaws.com"
# FILL THE MISSING VALUES ABOVE

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Leantime App
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ env.LEANTIME_TASK_DEFINITION }}
          service: ${{ env.ECS_LEANTIME_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          force-new-deployment: true
          run-task-tags: '[{"key": "", "value": ""} , ...]'
